### ISSUE TITLE
提交bug,下拉到底后，快速拖拽刷新页面，一直停留在下拉加载

### ISSUE THREAD

**Issue by neconano** [icewst/YTWebView#1]
rt

测试机型，小米4c
系统miui8

编译时候提示找不到android:scrollbarThumbVertical="@mipmap/pull_to_refresh_webview_scrollbar"，注释掉了，是否有影响

Error:(6, 37) No resource found that matches the given name (at 'scrollbarThumbVertical' with value '@mipmap/pull_to_refresh_webview_scrollbar').

**Comment by icewst** [comment]
1.android:scrollbarThumbVertica这个是自定义的一个滚动条，可能当时删除掉了
2.一直停留在下拉中？这个我看看。

非常感谢，我会尽快解决。
