### ISSUE TITLE
没法显示WebView的滚动条

### ISSUE THREAD

**Issue by BlackMagicHappy** [icewst/YTWebView#3]
我的手机是魅族， 系统是5.1的，没法显示出WebView的滚动条。

**Comment by icewst** [comment]
我尽快看看，请问你的手机具体型号是？

**Comment by icewst** [comment]
我的WebView没有对滚动条做任何设置，和你用默认WebView情况是一样的。
我看了，滚动条是有的，只是是一根白线，和百度的页面，刚好颜色一样，看不出来。
有方法可以设置滚动条演示，你可以看看
